src/Web/MVC/MsSystem.Web/Components/MenuViewComponent.cs
using JadeFramework.Core.Domain.Container;
using JadeFramework.Core.Domain.Entities;
using JadeFramework.Core.Domain.Permission;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MsSystem.Web.Components
{
    /// <summary>
    /// 菜单区分布视图
    /// </summary>
    public class MenuViewComponent : ViewComponent
    {
        private IPermissionStorageContainer _permissionStorage;

        public MenuViewComponent(IPermissionStorageContainer permissionStorage)
        {
            _permissionStorage = permissionStorage;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="isShowPage"></param>
        /// <param name="routeName"></param>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync(bool isShowPage = false)
        {

            string area = this.RouteData.Values["area"].ToString();
            string controller = this.RouteData.Values["controller"].ToString();
            string action = this.RouteData.Values["action"].ToString();
            RouteName routeName = new RouteName()
            {
                Action = action,
                Areas = area,
                Controller = controller
            };

            string url = string.IsNullOrEmpty(routeName.Areas)
                ? "/" + routeName.Controller + "/" + routeName.Action
                : "/" + routeName.Areas + "/" + routeName.Controller + "/" + routeName.Action;
            url = url.Trim().ToLower();
            var permission = await _permissionStorage.GetPermissionAsync();
            var menu = permission.Menus.FirstOrDefault(m => m.MenuUrl != null && m.MenuUrl.Trim().ToLower() == url);
            if (menu != null && isShowPage == false)
            {
                var list = CreateBtn(routeName, menu);
                return View(list);
            }
            else
            {
                if (isShowPage == true)
                {
                    List<string> list = new List<string>()
                    {
                        "<div class=\"btn-group btn-group-sm\">",
                        "<button type=\"button\" id=\"formSave\" class=\"btn btn-primary btn-sm btn-permission btn-permission-save\"><i class=\"fa fa-save\"></i><span class=\"ml5\">保存</span></button>",
                        "<button type=\"button\" id=\"formReturn\" class=\"btn btn-default btn-sm btn-permission\"><i class=\"fa fa-mail-reply\"></i><span class=\"ml5\">返回</span></button>",
                        "</div>"
                    };
                    return View(list);
                }
                else
                {
                    return View(new List<string>());
                }
            }
        }

        /// <summary>
        /// 创建菜单HTML
        /// </summary>
        /// <param name="routeName"></param>
        /// <param name="menu"></param>
        /// <returns></returns>
        private List<string> CreateBtn(RouteName routeName, Menu menu)
        {
            var buttons = menu.MenuButton;
            string btnId = routeName.Controller + "_" + routeName.Action + "_";
            var comBtns = buttons.OrderBy(m => m.ButtonType);
            List<string> list = new List<string>();
            List<string> list2 = new List<string>();
            list2.Add("<div class=\"btn-group btn-group-sm\">");
            foreach (var item in comBtns)
            {
                if (item.ButtonType == 1)//查看
                {
                    list.Add($"<div class=\"btn-group btn-group-sm\"><button class=\"btn btn-sm btn-permission btn-permission-search {item.ButtonClass}\" type=\"button\" id=\"{btnId + item.ButtonType}\"><i class=\"{item.Icon}\"></i><span class=\"ml5\">查询</span></button></div>" +
                        $"<div class=\"btn-group btn-group-sm\"><a id=\"ms_refresh\" class=\"btn btn-sm btn-permission\" title=\"刷新\"><i class=\"fa fa-refresh\"></i></a></div>");
                }
                else
                {
                    list2.Add($"<button class=\"btn btn-sm btn-permission {item.ButtonClass}\" type=\"button\" id=\"{btnId + item.ButtonType}\"><i class=\"{item.Icon}\"></i><span class=\"ml5\">{item.ButtonName}</span></button>");
                }
            }
            list2.Add("</div>");
            return list.Union(list2).ToList();
        }
    }
}

src/Web/MVC/MsSystem.Web/Components/WorkFlowSystemMenuViewComponent.cs
using JadeFramework.Core.Mvc.Extensions;
using JadeFramework.WorkFlow;
using Microsoft.AspNetCore.Mvc;
using MsSystem.Web.Areas.WF.Service;
using System.Threading.Tasks;

namespace MsSystem.Web.Components
{
    public class WorkFlowSystemMenuViewComponent : ViewComponent
    {
        private readonly IWorkFlowInstanceService workFlowInstanceService;

        public WorkFlowSystemMenuViewComponent(IWorkFlowInstanceService workFlowInstanceService)
        {
            this.workFlowInstanceService = workFlowInstanceService;
        }

        public async Task<IViewComponentResult> InvokeAsync(SystemFlowDto model)
        {
            model.UserId = HttpContext.User.ToUserIdentity().UserId.ToString();
            var process = await workFlowInstanceService.GetProcessForSystemAsync(model);
            process.FormContent = model.PageId;
            return View(process);
        }
    }
}

src/Web/MVC/MsSystem.Web/Areas/OA/Views/Leave/Index.cshtml
@using MsSystem.Web.Areas.WF.Infrastructure
@model Page<OaLeaveDto>
@{
    ViewData["Title"] = "员工请假";
    Layout = "~/Views/Shared/_LayoutJQ.cshtml";
}
@section scripts{
    <script>
        isrefresh = true;
        $(function(){
            $('.jquery-pager').pager({
                currentPageName: 'PageIndex',
                pageSizeName: 'PageSize'
            });
            $('#Leave_Index_2').click(function () {
                utils.menu.open({
                    dataUrl: '/OA/Leave/Show',
                    menuName: '员工请假填写'
                });
            });
            $('a[name=editform]').on('click', function () {
                var _this = $(this);
                var id = _this.attr('data-id');
                utils.menu.open({
                    dataUrl: '/OA/Leave/Show?id=' + id,
                    menuName: '员工请假' + _this.text()
                });
            });
        });
    </script>
}
<div class="wrapper-content">
    <div class="row">
        <div class="ibox">
            <div class="ibox-title text-right">
                @await Component.InvokeAsync("Menu")
            </div>
            <div class="ibox-content">
                <div class="full-height-scroll">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th class="w50"><input type="checkbox" id="ms_checkall" class="i-checks" /></th>
                                    <th class="w200">编号</th>
                                    <th>标题</th>
                                    <th class="w100">请假人</th>
                                    <th class="w150">创建时间</th>
                                    <th class="w100 text-center">流程状态</th>
                                    <th class="w100 text-center">操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Items)
                                {
                                    <tr>
                                        <td>
                                            <input type="checkbox" class="i-checks" value="@item.Id" />
                                        </td>
                                        <td>@item.LeaveCode</td>
                                        <td>@item.Title</td>
                                        <td>@item.UserName</td>
                                        <td>@item.CreateTime.ToDateTime().ToString("yyyy-MM-dd HH:mm:ss")</td>
                                        <td class="text-center">@Html.Raw(((WorkFlowStatus)item.FlowStatus).ToWorkFlowStatusIcon())</td>
                                        <td class="text-center"><a name="editform" data-id="@item.Id">@((WorkFlowStatus)item.FlowStatus == WorkFlowStatus.UnSubmit ? "编辑" : "查看")</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="jquery-pager" data-pageindex="@Model.PageIndex" data-pagesize="@Model.PageSize" data-datacount="@Model.TotalItems"></div>
            </div>
        </div>
    </div>
</div>

src/Web/MVC/MsSystem.Web/Areas/OA/Views/Leave/Show.cshtml
@model OaLeaveShowDto
@{
    ViewData["Title"] = "员工请假填写";
    Layout = "~/Areas/OA/Views/Shared/_Layout.cshtml";
}
@section css{
    <link href="~/ui/js/plugins/laydate/theme/default/laydate.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/ui/js/plugins/laydate/laydate.js"></script>
    <script>
        var optionParams = {
            'UserId': null,
            'FormId': $('input[name=PageId]').val()
        };
        var saveFormData = function (successcb) {
            var isvalidate = $('#flowform').valid();
            if (isvalidate === false) {
                return;
            }
            var url = "/OA/Leave/";
            var id = $('input[name=LeaveCode]').prev().val();
            if (id > 0) {
                url += "UpdateAsync";
            } else {
                url += "InsertAsync";
            }
            var param = {
                'Id': id,
                'Title': $('input[name=Title]').val(),
                'LeaveType': $('select[name=LeaveType]').val(),
                'StartTime': $('input[name=StartTime]').val(),
                'EndTime': $('input[name=EndTime]').val(),
                'Reason': $('textarea[name=Reason]').val()
            };
            axios.post(url, param).then(function (response) {
                if (response.data.IsError == false) {
                    $('input[name=PageId]').val(response.data.Data);
                    layer.msg('保存成功！', { icon: 1, time: 1000 }, function () {
                        if (typeof (successcb) == "function") {
                            successcb();
                        } else {
                            utils.menu.closeCurrentTab();
                        }
                    });
                } else {
                    layer.msg('保存失败！', { icon: 5, time: 1500 });
                }
            });
        };
        $(function () {
            var startDate = laydate.render({
                elem: '#StartTime',
                min: Date.now(),
                done: function (value, date) {
                    endDate.config.min = {
                        year: date.year,
                        month: date.month - 1,
                        date: date.date,
                    };
                    endDate.config.start = {
                        year: date.year,
                        month: date.month - 1,
                        date: date.date,
                    };
                }
            });
            var endDate = laydate.render({
                elem: '#EndTime',
                min: Date.now(),
                done: function (value, date) {
                    startDate.config.max = {
                        year: date.year,
                        month: date.month - 1,
                        date: date.date,
                    }
                }
            });
        });
    </script>
}
<div class="show-content">
    <div class="row p5">
        @await Component.InvokeAsync("WorkFlowSystemMenu", new SystemFlowDto { FormUrl = "/OA/Leave/Show", PageId = Model.Id == default(int) ? null : Model.Id.ToString() })
    </div>
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <form class="form-horizontal m-t" id="flowform">
                    <div class="form-group">
                        <label class="col-xs-3 col-sm-3 control-label">编号：</label>
                        <div class="col-xs-9 col-sm-9">
                            <input type="hidden" name="TableName" value="oa_leave" />
                            <input type="hidden" asp-for="Id" data-name="Id" name="PageId" />
                            <input type="text" asp-for="LeaveCode" class="form-control" placeholder="系统自动生成" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 col-sm-3 control-label"><span class="red">*</span>请假标题：</label>
                        <div class="col-xs-9 col-sm-9">
                            <input type="text" asp-for="Title" class="form-control required">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 col-sm-3 control-label">请假类型：</label>
                        <div class="col-xs-9 col-sm-9">
                            <span class="select-box inline">
                                <select class="select" asp-for="LeaveType">
                                    @foreach (var item in Enum<OaLeaveType>.AsEnumerable())
                                    {
                                        <option value="@((int)item)">@item.GetDescription()</option>
                                    }
                                </select>
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 col-sm-3 control-label"><span class="red">*</span>开始时间：</label>
                        <div class="col-xs-3 col-sm-3">
                            <input type="text" class="form-control w150 required" name="StartTime" value="@Model.StartTime.ToString("yyyy-MM-dd")" id="StartTime" />
                        </div>
                        <label class="col-xs-2 col-sm-2 control-label"><span class="red">*</span>结束时间：</label>
                        <div class="col-xs-4 col-sm-4">
                            <input type="text" class="form-control w150 required" name="EndTime" value="@Model.EndTime.ToString("yyyy-MM-dd")" id="EndTime" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 col-sm-3 control-label"><span class="red">*</span>请假原因：</label>
                        <div class="col-xs-9 col-sm-9">
                            <textarea asp-for="Reason" class="form-control required"></textarea>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>